import { Router } from "express";
import { getUsers, createUser, updateUser, deleteUser } from "../controllers/usersController.js";
import { requireAuth, requireRole } from "../middleware/auth.js";
const router = Router();
router.use(requireAuth, requireRole("SuperAdmin"));
router.get("/", getUsers);
router.post("/", createUser);
router.put("/:id", updateUser);
router.delete("/:id", deleteUser);
export default router;